SCREENWIDTH = 800
SCREENHEIGHT = 800

FPS = 60
ANIMATIONFPS = 24

CELLSIZE = 32

WORLDWIDTH = 100
WORLDHEIGHT = 100

WORLDPIXELWIDTH = WORLDWIDTH * CELLSIZE
WORLDPIXELHEIGHT = WORLDHEIGHT * CELLSIZE

POINTSPERBELT = 4